name: Deploy Lambda + Terraform

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ---------------------------
      # Step 1: Checkout Repo
      # ---------------------------
      - name: Checkout repo
        uses: actions/checkout@v3

      # ---------------------------
      # Step 2: Set up Python
      # ---------------------------
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      # ---------------------------
      # Step 3: Configure AWS
      # ---------------------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # ---------------------------
      # Step 4: Install Terraform
      # ---------------------------
      - name: Install Terraform
        uses: hashicorp/setup-terraform@v2

      # ---------------------------
      # Step 5: Terraform Init
      # ---------------------------
      - name: Terraform Init
        run: terraform -chdir=terraform init

      # ---------------------------
      # Step 6: Terraform Apply
      # ---------------------------
      - name: Terraform Apply
        run: |
          terraform -chdir=terraform apply -auto-approve \
            -var="aws_region=${{ secrets.AWS_REGION }}" \
            -var="sendgrid_api_key=${{ secrets.SENDGRID_API_KEY }}" \
            -var="ses_sender_email=${{ secrets.SES_SENDER_EMAIL }}"
